btn_sach.onclick=function(){
    img1.style.display='block';
    img2.style.display='block';
    img3.style.display='block';
    img4.style.display='block';
    img5.style.display='block';
    img6.style.display='block';
    img6.src='photo/Web-Dizayn-1.jpg';
    img5.src='photo/Web-Dizayn-2.png';
    img4.src='photo/Web-Dizayn-3.jpg';
    img3.src='photo/Web-Dizayn-4.jpg';
    img2.src='photo/v-d1.webp';
    img1.src='photo/v-d2.webp';
}

btn_smm.onclick=function(){
    img1.style.display='block';
    img2.style.display='block';
    img3.style.display='block';
    img4.style.display='block';
    img5.style.display='block';
    img6.style.display='block';
    img2.src='photo/Web-Dizayn-1.jpg';
    img1.src='photo/Web-Dizayn-2.png';
    img6.src='photo/Web-Dizayn-3.jpg';
    img4.src='photo/Web-Dizayn-4.jpg';
    img5.src='photo/v-d1.webp';
    img3.src='photo/v-d2.webp';
}

btn_web.onclick=function(){
    img1.style.display='block';
    img2.style.display='block';
    img3.style.display='block';
    img4.style.display='block';
    img5.style.display='block';
    img6.style.display='block';
    img1.src='photo/Web-Dizayn-1.jpg';
    img2.src='photo/Web-Dizayn-2.png';
    img3.src='photo/Web-Dizayn-3.jpg';
    img4.src='photo/Web-Dizayn-4.jpg';
    img5.src='photo/v-d1.webp';
    img6.src='photo/v-d2.webp';
}

btn_tik.onclick=function(){
    img1.style.display='block';
    img2.style.display='block';
    img3.style.display='block';
    img4.style.display='block';
    img5.style.display='block';
    img6.style.display='block';
    img5.src='photo/Web-Dizayn-1.jpg';
    img6.src='photo/Web-Dizayn-2.png';
    img3.src='photo/Web-Dizayn-3.jpg';
    img1.src='photo/Web-Dizayn-4.jpg';
    img4.src='photo/v-d1.webp';
    img2.src='photo/v-d2.webp';
}

btn_komp.onclick=function(){
    img1.style.display='block';
    img2.style.display='block';
    img3.style.display='block';
    img4.style.display='block';
    img5.style.display='block';
    img6.style.display='block';
    img4.src='photo/Web-Dizayn-1.jpg';
    img1.src='photo/Web-Dizayn-2.png';
    img6.src='photo/Web-Dizayn-3.jpg';
    img2.src='photo/Web-Dizayn-4.jpg';
    img5.src='photo/v-d1.webp';
    img3.src='photo/v-d2.webp';
}

btn_dulus.onclick=function(){
    img1.style.display='block';
    img2.style.display='block';
    img3.style.display='block';
    img4.style.display='block';
    img5.style.display='block';
    img6.style.display='block';
    img1.src='photo/Web-Dizayn-1.jpg';
    img4.src='photo/Web-Dizayn-2.png';
    img3.src='photo/Web-Dizayn-3.jpg';
    img2.src='photo/Web-Dizayn-4.jpg';
    img5.src='photo/v-d1.webp';
    img6.src='photo/v-d2.webp';
}